#!/usr/bin/env bash
# configure nginx server to listen for port 80

# remove default nginx configuration
rm /etc/nginx/sites-enabled/default

# configure nginx on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx 
service nginx restart
