#!/usr/bin/env bash
# ssh client configuration

Host *
    PasswordAuthentification no
    IdentifyFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentification yes
    GSSAPIDelegateCredentials no
